services:
  app:
    image: ghcr.io/heman/docker-workflow:latest
    restart: "no"

    command: ["sleep", "infinity"]

    environment:
      DATABASE_URL: ${DATABASE_URL}

    ports:
      - "18000:8000"